fix(email): Fix sending re-invites to all emails
ERROR: UndefinedMagicMethod - lib/Controller/RoomController.php:1459:22
Magic method OCA\Talk\Model\Attendee::getattendee does not exist (see https://psalm.dev/219)

Signed-off-by: Joas Schilling <coding@schilljs.com>