Fix upgrade with Postgres and Oracle
Exception: Database error when running migration 14000Date20220330141647 for app spreed
An exception occurred while executing a query: SQLSTATE[42883]: Undefined function: 7 ERROR:  operator does not exist: character varying = bigint
LINE 1: ...LEFT JOIN "oc_filecache" "f" ON "s"."item_source" = "f"."fil...
                                                             ^
HINT:  No operator matches the given name and argument types. You might need to add explicit type casts.

Signed-off-by: Joas Schilling <coding@schilljs.com>